### ISSUE TITLE
[CONUMM] - liens footer

### ISSUE THREAD

**Issue by JulienParis** [co-demos/PING-carto#13]
@GreBarb il me faudra la liste des liens à indiquer dans le footer du site carto CONUMM, actuellement ceux en prod sont visibles ici : https://conumm.netlify.com

**Comment by GreBarb** [comment]
Voici la liste :
ILS SOUTIENNENT LE PROJET
Les deux liens sont bon donc RAS

AUTRE CARTOGRAPHIE POUVANT VOUS INTERESSER
Formation des bénévoles _le Portail Régionnal_ https://formations-benevoles-paysdelaloire.org/
Cartographie des tiers lieux en Pays de la Loire ??? (la futur cartographie de PiNG :-) )
Point d'Appui au Numérique Associatif https://www.helloasso.com/pana/
Les Bons Clics https://www.lesbonsclics.fr/fr/cartographie

**Comment by GreBarb** [comment]
CONUMM
Je me demande si il ne faudrait pas séparer "les outils de valorisation de données" "code source" "login back office" dans une nouvelle colonne... Une colonne que l'on pourrait intitulée "les outils"
Et garder dans la colonne CONUMM :
- Le site de CONUMM https://conumm.fr/
- Qui sommes-nous ? https://conumm.fr/qui-sommes-nous/ 
- Nos actions https://conumm.fr/actions/ 
- Mentions légales

**Comment by JulienParis** [comment]
fait (à part les liens login et outils, pour plus tard)
